# Generated by Django 5.2.17 on 2026-09-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcript_generator", "0003_rename_youtube_title_articlepost_video_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articlepost",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="articlepost",
            name="error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="articlepost",
            name="stage",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="articlepost",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Queued"),
                    ("processing", "Processing"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="done",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="articlepost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="articlepost",
            name="generated_content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="articlepost",
            name="video_title",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
