# Generated by Django 5.2.17 on 2026-09-29 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcript_generator", "0004_background_jobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepost",
            name="chapters",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="articlepost",
            name="key_takeaways",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="articlepost",
            name="quiz",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="articlepost",
            name="transcript",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="transcript_generator.articlepost",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
