# Generated by Django 5.2.17 on 2026-09-29 21:12

from django.db import migrations, models

from transcript_generator.services import PipelineError, extract_video_id


def backfill_video_ids(apps, schema_editor):
    ArticlePost = apps.get_model("transcript_generator", "ArticlePost")
    for article in ArticlePost.objects.filter(video_id="").only("id", "youtube_link"):
        try:
            article.video_id = extract_video_id(article.youtube_link)
        except PipelineError:
            continue
        article.save(update_fields=["video_id"])

class Migration(migrations.Migration):

    dependencies = [
        ("transcript_generator", "0005_richer_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepost",
            name="video_id",
            field=models.CharField(blank=True, db_index=True, max_length=11),
        ),
        migrations.RunPython(backfill_video_ids, migrations.RunPython.noop),
    ]
